Update docker-compose

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -14,8 +14,10 @@ services:
       - sh
       - -c
       - |-
+        # trigger complete failure if any fail
+        set -e
         # secret check
-        echo "${SAMPLE_MESSAGE}raphael" | base64 -w 0 && echo
+        echo -n "${SAMPLE_MESSAGE}bernie" | base64
         # additional test dependencies (need to update)
         pip install . pytest pytest-cov
         # syntax tests
